import axios from "axios";
import { getIdToken } from "firebase/auth";
import { auth } from "../firebase";

// Central API utility (frontend ↔ backend)
// Base URL: from env or fallback
const client = axios.create({
  baseURL: import.meta.env.VITE_API_URL || "https://expense-tracker-rouge-chi-43.vercel.app",
  headers: {
    "Content-Type": "application/json",
  },
});

client.interceptors.request.use(async (config) => {
  try {
    const currentUser = auth.currentUser;
    if (currentUser) {
      const token = await getIdToken(currentUser);
      if (token) {
        config.headers = config.headers || {};
        config.headers.Authorization = `Bearer ${token}`;
      }
    }
  } catch {
    // ignore auth token attach errors
  }
  return config;
});

client.interceptors.response.use(
  (response) => response,
  (error) => {
    const message = error.response?.data?.message || error.message;
    return Promise.reject(new Error(message));
  }
);

function normalizeExpense(e) {
  return {
    id: e?._id || e?.id,
    amount: Number(e?.amount) || 0,
    category: (e?.category || "other").toLowerCase(),
    date: e?.date || new Date().toISOString(),
    note: e?.note || "",
    isRecurring: Boolean(e?.isRecurring),
    recurringType: e?.recurringType || null,
    isAutoGenerated: Boolean(e?.isAutoGenerated),
  };
}

function pickData(res) {
  if (!res?.data) return null;
  if (res.data.success === false) {
    throw new Error(res.data.message || "Request failed.");
  }
  return res.data.data;
}

export const api = {
  async fetchProfile() {
    try {
      const res = await client.get("/api/profile");
      return pickData(res);
    } catch (error) {
      console.error("API fetchProfile Error:", error);
      throw error;
    }
  },

  async saveProfile(payload) {
    try {
      const res = await client.put("/api/profile", payload);
      return pickData(res);
    } catch (error) {
      console.error("API saveProfile Error:", error);
      throw error;
    }
  },

  async fetchAnalyticsSummary(workspaceId) {
    try {
      const wId = workspaceId || localStorage.getItem("xpense_active_workspace")?.replace(/"/g, '') || "default";
      const res = await client.get(`/api/analytics/summary?workspaceId=${wId}`);
      return pickData(res);
    } catch (error) {
      console.error("API fetchAnalyticsSummary Error:", error);
      throw error;
    }
  },

  async fetchExpenses(workspaceId) {
    try {
      const wId = workspaceId || localStorage.getItem("xpense_active_workspace")?.replace(/"/g, '') || "default";
      const res = await client.get(`/api/expenses?workspaceId=${wId}`);
      const data = pickData(res) || [];
      return Array.isArray(data) ? data.map(normalizeExpense) : [];
    } catch (error) {
      console.error("API fetchExpenses Error:", error);
      throw error;
    }
  },

  async addExpense(expense) {
    try {
      const wId = expense.workspaceId || localStorage.getItem("xpense_active_workspace")?.replace(/"/g, '') || "default";
      const res = await client.post("/api/expenses/add", {
        amount: expense.amount,
        category: expense.category,
        note: expense.note,
        date: expense.date,
        workspaceId: wId,
        isRecurring: Boolean(expense.isRecurring),
        recurringType: expense.isRecurring ? expense.recurringType : null,
      });
      const data = pickData(res);
      return normalizeExpense(data);
    } catch (error) {
      console.error("API addExpense Error:", error);
      throw error;
    }
  },

  async deleteExpense(id, workspaceId) {
    try {
      const wId = workspaceId || localStorage.getItem("xpense_active_workspace")?.replace(/"/g, '') || "default";
      const res = await client.delete(`/api/expenses/${id}?workspaceId=${wId}`);
      const data = pickData(res);
      return normalizeExpense(data);
    } catch (error) {
      console.error("API deleteExpense Error:", error);
      throw error;
    }
  },

  async upgradePlan(planName) {
    try {
      const res = await client.post("/api/plan/upgrade", { plan: planName });
      return pickData(res);
    } catch (error) {
      console.error("API upgradePlan Error:", error);
      throw error;
    }
  },

  async updateExpense(id, expense) {
    try {
      const wId = expense.workspaceId || localStorage.getItem("xpense_active_workspace")?.replace(/"/g, '') || "default";
      const res = await client.put(`/api/expenses/${id}`, {
        amount: expense.amount,
        category: expense.category,
        note: expense.note,
        date: expense.date,
        workspaceId: wId,
      });
      const data = pickData(res);
      return normalizeExpense(data);
    } catch (error) {
      console.error("API updateExpense Error:", error);
      throw error;
    }
  },

  async generateInviteLink(workspaceId) {
    try {
      const res = await client.post(`/api/invite/${workspaceId}`);
      const data = res?.data;
      if (!data?.success) throw new Error(data?.message || "Failed to generate invite link.");
      return { ok: true, inviteLink: data.inviteLink };
    } catch (error) {
      console.error("API generateInviteLink Error:", error);
      return { ok: false, message: error.message };
    }
  },

  async verifyInviteToken(token) {
    try {
      const res = await client.post("/api/invite/verify", { token });
      const data = res?.data;
      if (!data?.success) throw new Error(data?.message || "Invalid invite link.");
      return { ok: true, workspaceId: data.workspaceId, role: data.role, name: data.name };
    } catch (error) {
      console.error("API verifyInviteToken Error:", error);
      return { ok: false, message: error.message };
    }
  },

  async fetchWorkspaces() {
    try {
      const res = await client.get("/api/workspaces");
      return pickData(res) || [];
    } catch (error) {
      console.error("API fetchWorkspaces Error:", error);
      throw error;
    }
  },

  async createWorkspace(name, id) {
    try {
      const res = await client.post("/api/workspaces", { name, id });
      return { ok: true, data: res.data };
    } catch (error) {
      console.error("API createWorkspace Error:", error);
      return { ok: false, message: error.message };
    }
  },

  async deleteWorkspace(id) {
    try {
      const res = await client.delete(`/api/workspaces/${id}`);
      return { ok: true, data: res.data };
    } catch (error) {
      console.error("API deleteWorkspace Error:", error);
      return { ok: false, message: error.message };
    }
  },

  /**
   * Permanently delete the authenticated user's account.
   * The server deletes all DB data first, then the Firebase Auth user.
   * Returns { ok: true } on success or { ok: false, message } on failure.
   */
  async deleteAccount() {
    try {
      const res = await client.delete("/api/profile/me");
      const data = res?.data;
      if (data?.success === false) throw new Error(data.message || "Delete failed.");
      return { ok: true };
    } catch (error) {
      return { ok: false, message: error.message || "Failed to delete account." };
    }
  },
};
