/**
 * Recurring Expense Cron Job
 * Runs at midnight UTC every day.
 * Finds all recurring expenses whose nextRunDate has passed,
 * creates a new expense copy, and advances nextRunDate.
 *
 * Usage: required by server.js — do NOT run this file directly.
 *
 * Install dependency first:
 *   npm install node-cron
 */

const cron = require("node-cron");
const Expense = require("../models/Expense");

function computeNextRunDate(base, type) {
  const d = new Date(base);
  if (type === "weekly")  d.setUTCDate(d.getUTCDate() + 7);
  if (type === "monthly") d.setUTCMonth(d.getUTCMonth() + 1);
  return d;
}

function startRecurringCron() {
  // Runs every day at 00:00 UTC
  cron.schedule("0 0 * * *", async () => {
    const now = new Date();
    console.log(`[CRON] Running recurring expense job at ${now.toISOString()}`);

    try {
      // Find all recurring templates whose nextRunDate is in the past
      const due = await Expense.find({
        isRecurring:  true,
        nextRunDate:  { $lte: now },
        isAutoGenerated: false,   // only process original templates
      });

      if (due.length === 0) {
        console.log("[CRON] No recurring expenses due today.");
        return;
      }

      let created = 0;
      for (const template of due) {
        // Create the auto-generated copy with today as the date
        await Expense.create({
          userId:          template.userId,
          workspaceId:     template.workspaceId,
          amount:          template.amount,
          category:        template.category,
          date:            now,
          note:            template.note,
          isRecurring:     false,      // copies are NOT new templates
          isAutoGenerated: true,
          parentExpenseId: template._id,
        });

        // Advance the template's nextRunDate forward by one period
        const nextRunDate = computeNextRunDate(template.nextRunDate, template.recurringType);
        await Expense.findByIdAndUpdate(template._id, { nextRunDate });

        created++;
        console.log(
          `[CRON] Created recurring copy for expense ${template._id} ` +
          `(user: ${template.userId}, amount: ${template.amount}). ` +
          `Next run: ${nextRunDate.toISOString()}`
        );
      }

      console.log(`[CRON] Done. Created ${created} expense(s).`);
    } catch (err) {
      console.error("[CRON] Error running recurring expense job:", err.message);
    }
  }, {
    timezone: "UTC",   // always explicit — no local timezone surprises
  });

  console.log("[CRON] Recurring expense scheduler started (runs daily at 00:00 UTC).");
}

module.exports = { startRecurringCron };
