const mongoose = require("mongoose");

/**
 * Expense model
 * - `timestamps: true` automatically adds `createdAt` and `updatedAt`
 * - `workspaceId` scopes expenses per workspace (default = "default")
 * - `isRecurring` / `recurringType` / `nextRunDate` support recurring expenses
 */
const expenseSchema = new mongoose.Schema(
  {
    /** Firebase Auth uid — scopes expenses per user */
    userId: {
      type: String,
      required: true,
      index: true,
    },

    /** Workspace isolation — defaults to "default" workspace */
    workspaceId: {
      type: String,
      default: "default",
      index: true,
    },

    amount: {
      type: Number,
      required: true,
    },
    category: {
      type: String,
      required: true,
      enum: ["food", "travel", "shopping", "entertainment", "utilities", "other"],
    },
    date: {
      type: Date,
      default: Date.now,
    },
    note: {
      type: String,
      trim: true,
    },

    // ── Recurring expense fields ────────────────────────────────────────────
    isRecurring: {
      type: Boolean,
      default: false,
    },
    recurringType: {
      type: String,
      enum: ["monthly", "weekly"],
      default: null,
    },
    /** UTC date when the next auto-copy of this expense should be created */
    nextRunDate: {
      type: Date,
      default: null,
    },

    /** True for auto-generated copies produced by the cron job (not user-created) */
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    /** Links auto-generated copies back to their parent template */
    parentExpenseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Expense",
      default: null,
    },
  },
  { timestamps: true }
);

// Compound index for efficient recurring-expense queries in the cron job
expenseSchema.index({ isRecurring: 1, nextRunDate: 1 });

module.exports = mongoose.model("Expense", expenseSchema);
